apache/openwhisk-runtime-nodejs

- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
This will allow to push a new image to dockerhub with nodejs 6.11.4
> update nodejs:6 runtime to 6.11.4

- README.md
- settings.gradle
Attempting build with OPENWHISK_HOME unset (and openwhisk not in a specific default) caused an unhelpful error message:
```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/jonpspri/Projects/openwhisk-runtime-nodejs/tests/build.gradle' line: 23
* What went wrong:
A problem occurred evaluating project ':tests'.
> Could not get unknown property 'sourceSets' for project ':whisktests' of type org.gradle.api.Project.
```
Changes instead produce an error message that identifies the problem and correct it:
```
FAILURE: Build failed with an exception.
* Where:
Settings file '/Users/jpspring/Projects/incubator-openwhisk-runtime-nodejs/settings.gradle' line: 5
* What went wrong:
Environment variable OPENWHISK_HOME must point to a valid OpenWhisk build
```
> Add more descriptive error message for unset OPENWHISK_HOME

- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
> bumps to nodejs 6.12, openwhisk 3.10

- .travis.yml
This issue extends functionality of the Travis verification process so that on a merge from the Master branch Travis will push out a tag "master" for the "openwhisk/nodejs6action" and "openwhisk/action-nodejs-v8" Docker images to Docker.
> update open nodejs runtime to push master tag to docker from Travis

- LICENSE.txt
- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/package.json
A new version of the openwhisk NPM package was released and both of the NodeJS runtimes, version 6 and 8, had to be updated to pick up that change.  
Issue tracking here: https://github.com/apache/incubator-openwhisk/issues/3597
> update openwhisk npm package for nodejs6 and nodejs8

- .travis.yml
This PR is to lock down the Deploy step of the Travis.yml so that it only executes when the repo matches the "upstream" repo, 'incubator-openwhisk-runtime-nodejs'
> add to travis.yml the runtime repo to the deploy block

- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
The NodeJS runtime had a security patch released.  
This bumped the versions for NodeJS 6 & 8 from 
NodeJS6 went from 6.14.2 -> 6.14.3
NodeJS8 went from 8.11.2 -> 8.11.3
This PR is simply to bump the version.
> update nodejs 6 & 8 to latest security patch

- .travis.yml
There was a typo in the repo name in the .travis.yml , the repo 'incubator-openwhisk-runtime-nodejs' was incorrectly entered as 'openwhisk-incubator-runtime-nodejs'
> fix issue with travis repo misspelling

- tools/travis/build.sh
@chetanmeh I think this shouldn't be necessary and indicates an overly inclusive compilation step in this repo but the patch should resolve the Travis failure on master.
```
* What went wrong:
Could not resolve all files for configuration ':tests:testCompileClasspath'.
> Could not find org.apache.openwhisk:openwhisk-admin-tools:1.0.0-SNAPSHOT.
Searched in the following locations:
https://repo.maven.apache.org/maven2/org/apache/openwhisk/openwhisk-admin-tools/1.0.0-SNAPSHOT/maven-metadata.xml
https://repo.maven.apache.org/maven2/org/apache/openwhisk/openwhisk-admin-tools/1.0.0-SNAPSHOT/openwhisk-admin-tools-1.0.0-SNAPSHOT.pom
https://repo.maven.apache.org/maven2/org/apache/openwhisk/openwhisk-admin-tools/1.0.0-SNAPSHOT/openwhisk-admin-tools-1.0.0-SNAPSHOT.jar …
```
> Build wskadmin-next.

- core/nodejs6Action/CHANGELOG.md
- core/nodejs8Action/CHANGELOG.md
- core/nodejsActionBase/src/service.js
- tests/src/test/scala/runtime/actionContainers/NodeJsActionContainerTests.scala
Adds a check in the init-handler to report an error if initialization is attempted more than once.
Also:
- Moves state setting out of `doInit` so that all state setting is localized to the route handlers.
- Moves `console.error` messages around so that they appear before the sentinel on init and run errors.
@tysonnorris having thought about this in the context of #41, I think we can achieve both mode by guarding the check in the run handler but leaving `state` otherwise in place.
Closes https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues/70.
> Tightens logic and reports more meanigful error message when attempting to initialize more than once.

- core/nodejsActionBase/src/service.js
This allows for the customized invoker with an SPI to send more variables in the run handler
@eweiter could you review this PR.
> remove hardcoded env variables for run handler

- core/nodejsActionBase/runner.js
- tests/src/test/scala/runtime/actionContainers/NodeJs8ActionContainerTests.scala
Return error string from errors and log stack trace for rejected promises.
> Fixes #63 - Support errors thrown from async functions

- core/nodejs10Action/Dockerfile
Since `nodejs:8` is based on jessie, is best to have the new runtime `nodejs:10` depend on `stretch`
> use stretch instead of jessie for nodejs10

- core/nodejs10Action/Dockerfile
- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
bump nodejs versions 10.15.0, 8.15.0, 6.16.0
https://nodejs.org/en/blog/release/v10.15.0/
https://nodejs.org/en/blog/release/v8.15.0/
https://nodejs.org/en/blog/release/v6.16.0/
> bump nodejs versions 10.15.0, 8.15.0, 6.16.0

- core/nodejs10Action/Dockerfile
- core/nodejs8Action/Dockerfile
- core/nodejsActionBase/Dockerfile
http://www.graphicsmagick.org: GM is distributed under an X11-style license (MIT License), approved by the Open Source Initiative, recommended for use by the OSSCC, and compatible with the GNU GPL.
> Add graphicsmagick to the base images.

- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/Dockerfile
- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
* Security updates
* https://nodejs.org/en/blog/release/v10.15.2/
* https://nodejs.org/en/blog/release/v8.15.1/
* https://nodejs.org/en/blog/release/v6.17.0/
> bump nodejs versions 10.15.2, 8.15.1, 6.17.0

- core/nodejsActionBase/app.js
- core/nodejsActionBase/src/service.js
It appears that the code was attempting to use the Node Express "use()" middleware to intercept and return a 500 error if the runtime was hit by any requests not ```/init``` or ```/run``` as follows:
```
app.use(function (err, req, res, next) {  // <== use without “err” parm.
console.error(err.stack); // <== REMOVE since "err" would no longer be a valid parm.
res.status(500).json({error: "Bad request."});
});
```
however, the method only has 3 valid parms. so it appears Node Express ignored the middle filter registration completely and the code was never invoked since it had too many parms. That is, the "err" parm. (as the first parm.) was "extra" and the signature had too many args.
This PR removes the "err" parm., as well as the now invalid console.error() call.
Please note (in …
> Add use() method to short-circuit requests with no route handlers

- core/nodejsActionBase/app.js
- core/nodejsActionBase/src/service.js
- tests/src/test/scala/runtime/actionContainers/NodeJsActionContainerTests.scala
This is part of the work related to https://github.com/apache/incubator-openwhisk/issues/4558 and depends on https://github.com/apache/incubator-openwhisk/pulls/4559.
> Export activation arguments to environment during initialization.

- core/nodejs10Action/package.json
- core/nodejs12Action/package.json
- core/nodejs8Action/package.json
- core/nodejsActionBase/package.json
This PR fixes composer, which requires `redis` and `uuid` modules.
See the [discussion](https://lists.apache.org/thread.html/beda24f3568164b5f750b3a91915ec9e275d878ae0e5c008cd0fbf3d@%3Cdev.openwhisk.apache.org%3E) on the dev list for more details.
> Add redis and uuid npm modules

- core/nodejs10Action/Dockerfile
- core/nodejs12Action/Dockerfile
- core/nodejs8Action/Dockerfile
> bump node 8,10,12 base docker images to consume upstream security fixes

- NOTICE.txt
- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/package.json
- core/nodejs12Action/CHANGELOG.md
- core/nodejs12Action/package.json
- core/nodejs6Action/CHANGELOG.md
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/package.json
bump openwhisk-client-js version to 3.21.1
update CHANGELOG.md for node 8,10,12
update end year in NOTICE
> release prep

- core/nodejs10Action/knative/Dockerfile
`package.json` was dropped from the version specific dir in PR #171. Reflecting the same change in Dockefile which is being used by Knative.
> updating the package.json path

- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/Dockerfile
- core/nodejs12Action/CHANGELOG.md
- core/nodejs12Action/Dockerfile
- core/nodejs14Action/CHANGELOG.md
- core/nodejs14Action/Dockerfile
Update the NodeJS to gather fixes
- Node.js v10.22.1 
- Node.js v12.18.4 
- Node.js v14.11.0
> Update the NodeJs runtimes to gather fixes

- core/nodejsActionBase/Dockerfile
stretch switched to node 15.1 about 24 hours ago.  This causes the build to fail (which we need to look into at some point), but as a general rule we should probably be using the most recent lts version, not the most recent dev version when building the base image.
For the record, the build error with node 15.1 was:
```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--no-package-lock',
0 verbose cli   '--production'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v15.1.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 4ms
7 timing …
```
> use lts-stretch (not stretch) as base image of nodejsActionBase

- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/Dockerfile
- core/nodejs12Action/CHANGELOG.md
- core/nodejs12Action/Dockerfile
- core/nodejs14Action/CHANGELOG.md
- core/nodejs14Action/Dockerfile
Upate runtimes to 
v14.15.1
v12.19.1
v10.23.0
to pick up fixes
> Gather NodeJS fixes

- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/Dockerfile
- core/nodejs12Action/CHANGELOG.md
- core/nodejs12Action/Dockerfile
- core/nodejs14Action/CHANGELOG.md
- core/nodejs14Action/Dockerfile
Update NodeJs to 10.24.0, 12.21.0 and 14.16.0 to gather fixes
> Update NodeJs to gather fixes

- settings.gradle
- tests/build.gradle
This may fix the build issue with the Akka family.
> Constraint all transitive akka-* dependencies

- core/nodejs12Action/CHANGELOG.md
- core/nodejs12Action/Dockerfile
- core/nodejs14Action/CHANGELOG.md
- core/nodejs14Action/Dockerfile
- Update Node to 14.17.5 and 12.22.5 to get latest security fixes.
> Update Node to 14.17.5 and 12.22.5.

- core/nodejs16Action/Dockerfile
Update to latest Debian release as Stretch support runs out this year
> Update nodejs16 base image to stay up do date

- core/nodejsActionBase/app.js
- core/nodejsActionBase/package.json
- core/nodejsActionBase/runner.js
adapt serialize-error to use a dynamic import instead of deprecated require
use express.json to replace bodyParser.json (remove bodyparser)
> Update package.json packages to latest version

- core/nodejs16Action/Dockerfile
This is for convenience so customers can package their actions inside of the runtime.
> Install zip

- core/nodejs16Action/CHANGELOG.md
- core/nodejs16Action/Dockerfile
Setting Nodejs 16 image to `node:16-bullseye` to get latest vulnerability fixes
> Update Nodejs 16 base image

- .travis.yml
This bings the machines to the build vm to a more up to date ubuntu version which should also reduce the risk of loosing support for the version
and update build java version to 11
> Update travis build vm dist form xenial to focal

- .github/workflows/ci.yaml
I believe this is now a full replacement for our existing Travis CI based workflow for this repository. 
I've been testing on my fork and it looks good.  Assuming it also looks good on the real repo (including the cron job to drive publishing of new images a few times a week), we should be able to fairly easily adapt the workflow file to the rest of our runtime repos.
I decided to port as much of the workflow as possible to a native GHA idioms and not just invoke our legacy scripts (which had accumulated a fair amount of historical baggage).
> GitHub action to replace Travis CI build/test/publish logic

- core/nodejsActionBase/runner.js
Install modules specified in package.json during initialisation as a alternative to packageing them. Detect if the node_modules directory is  missing and installes the node modules.
> Add functionality to install modules during init

- core/nodejsActionBase/runner.js
- Use environment variable OW_ENABLE_INIT_INSTALL ('true', 'false') to decide if 'npm install' during init should be done or not. The default is 'true' (do an install). Reason to do not run the 'npm install' is that takes time and that production load may not want to install untested module versions.
> Make 'npm install' during init configurable.

- .github/workflows/on-demand.yaml
This change enables an on-demand workflow to run in the downstream repo.
It is the equivalent change of the one in the core repo.
https://github.com/apache/openwhisk/blob/master/.github/workflows/0-on-demand.yaml
> Add an on-demand workflow
