- .travis.yml
- ansible/environments/local/group_vars/all
- ansible/environments/local/hosts
- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
- core/nodejs8Action/package.json
- settings.gradle
> update npm package openwhisk 3.11.0 and Node.js LTS

- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
> Update nodejs 6.14 and 8.11

- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
- core/nodejsActionBase/Dockerfile
To add license headers to 5 files.
Closes issue #25.
> Add license headers

- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
Updating the Node.js runtime version for both NodeJS 6 and NodeJS 8
NodeJS 6 from `6.14.1` -> `6.14.2`
NodeJS 8 from `8.11.1` -> `8.11.2`
> update nodejs6 -> 6.14.2, nodejs8 -> 8.11.2

- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/package.json
> update openwhisk package 3.15.0 -> 3.16.0

- core/nodejs6Action/CHANGELOG.md
- core/nodejs8Action/CHANGELOG.md
- tests/src/test/scala/runtime/actionContainers/NodeJs8ActionContainerTests.scala
This updates the Changelog files to document the change that occurred in pull request #73
> update Changelogs for PR #73

- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
> Update nodejs for Aug/2018 security patches

- tools/travis/publish.sh
> push a hashcommit of the image in travis publish

- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
> update to 8.12.0 LTS

- core/nodejs6Action/Dockerfile
- core/nodejs8Action/package.json
- core/nodejsActionBase/package.json
- core/nodejsActionBase/runner.js
> serialize errors

- .travis.yml
- README.md
- core/nodejs10Action/.dockerignore
- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/Dockerfile
- core/nodejs10Action/build.gradle
- core/nodejs10Action/package.json
- tests/dat/docker/nodejs10docker/Dockerfile
- tests/dat/docker/nodejs10docker/build.gradle
- tests/dat/docker/nodejs10docker/package.json
- tests/src/test/scala/runtime/actionContainers/NodeJs10ActionContainerTests.scala
- tests/src/test/scala/runtime/actionContainers/NodeJs10ConcurrentTests.scala
- tests/src/test/scala/runtime/actionContainers/NodeJs6ConcurrentTests.scala
- tests/src/test/scala/runtime/actionContainers/NodeJs8ConcurrentTests.scala
- tools/travis/publish.sh
> Add support for NodeJS10

- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/Dockerfile
- core/nodejs6Action/CHANGELOG.md
- core/nodejs6Action/Dockerfile
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/Dockerfile
> Update to latest nodejs security release november-2018

- core/nodejs10Action/Dockerfile
Add worker experimental flag for 10.x for more info here:
- https://nodejs.org/docs/latest-v10.x/api/worker_threads.html
- https://medium.com/dailyjs/threads-in-node-10-5-0-a-practical-intro-3b85a0a3c953
> Add worker experimental flag for 10.x

- core/nodejsActionBase/app.js
- core/nodejsActionBase/platform/knative.js
- core/nodejsActionBase/src/service.js
- Bringing @mrutkows's changes on "Make knative init/run logic more efficient based upon type of request (body) data" 
- eslint with ```{
"extends": "strongloop",
"rules": {
"indent": [4],
"max-len": [2, 120, 8]
}
}```
- addressing @rabbah's latest comments on PR #119
> Follow up on Knative PR - 119

- .travis.yml
Related to #126
Forgot to include this in the last PR... doh.
> Update Travis file to build & push Node.js v12 image to Docker Hub.

- core/nodejsActionBase/runner.js
This looks like dead code to me.
> Remove deadcode.

- core/nodejs10Action/Dockerfile
- core/nodejs10Action/knative/Dockerfile
- core/nodejsActionBase/runner.js
- core/nodejsActionBase/src/service.js
This PR applies refactoring and JS-isms, and intends no semantic changes. It is best to review each of the commits on its own as I grouped them logically into their change sets. Ignoring white space is also advised.
Note while some `lets` may be constants, the use of `let` is sometimes preferred to keep the scope of the variable scoped to its nearest `{}`.
> Refactoring of the service and runner, no semantic changes intended.

- core/nodejsActionBase/runner.js
- tests/src/test/scala/runtime/actionContainers/NodeJsActionContainerTests.scala
This addresses a regression noted in https://github.com/apache/incubator-openwhisk/pull/4514.
FYI @mhenke1.
> Global scope eval.

- core/nodejsActionBase/runner.js
- core/nodejsActionBase/src/service.js
- tests/src/test/scala/runtime/actionContainers/NodeJsActionContainerTests.scala
This commit partially reverts runner initialization and addresses #138.
Best to review this ignoring white space.
> Reverts runner refactoring changes.

- tests/src/test/scala/runtime/actionContainers/NodeJsActionContainerTests.scala
See https://github.com/apache/openwhisk/pull/4761.
> Update for action version.

- core/nodejsActionBase/runner.js
- tests/src/test/scala/runtime/actionContainers/NodeJsActionContainerTests.scala
Fixes https://github.com/apache/openwhisk-runtime-nodejs/issues/14.
> Support exports.main for simple files.

- .travis.yml
- README.md
- core/nodejs14Action/.dockerignore
- core/nodejs14Action/CHANGELOG.md
- core/nodejs14Action/Dockerfile
- core/nodejs14Action/build.gradle
- core/nodejs14Action/package.json
- tests/dat/docker/nodejs14docker/Dockerfile
- tests/dat/docker/nodejs14docker/build.gradle
- tests/dat/docker/nodejs14docker/package.json
- tests/src/test/scala/runtime/actionContainers/NodeJs10ConcurrentTests.scala
- tests/src/test/scala/runtime/actionContainers/NodeJs12ConcurrentTests.scala
- tests/src/test/scala/runtime/actionContainers/NodeJs14ActionContainerTests.scala
- tests/src/test/scala/runtime/actionContainers/NodeJs14ConcurrentTests.scala
- tools/travis/publish.sh
I was inspired by this [tweet](https://twitter.com/openwhisk/status/1259907986471952385) to make a contribution to this project!
Please let me know if something's not right.
> support for Node.js v14

- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/package.json
- core/nodejs12Action/CHANGELOG.md
- core/nodejs12Action/package.json
- core/nodejs14Action/CHANGELOG.md
- core/nodejs14Action/package.json
- core/nodejs8Action/CHANGELOG.md
- core/nodejs8Action/package.json
- core/typescript37Action/Dockerfile
- core/typescript37Action/bin/compile
- core/typescript37Action/lib/launcher.ts
> Update npm openwhisk version.

- README.md
> Updated reference to runtime.json in README.md

- core/nodejs10Action/CHANGELOG.md
- core/nodejs10Action/Dockerfile
- core/nodejs12Action/CHANGELOG.md
- core/nodejs12Action/Dockerfile
- core/nodejs14Action/CHANGELOG.md
- core/nodejs14Action/Dockerfile
Update to NodeJS v10.23.2, v12.20.1 and v14.15.4
> Update NodeJs to gather fixes

- core/typescript37Action/Dockerfile
This follows the pattern used in other repos to allow builds to select where to build source from.
> Update from source build.

- core/nodejs12Action/CHANGELOG.md
- core/nodejs12Action/Dockerfile
- core/nodejs14Action/CHANGELOG.md
- core/nodejs14Action/Dockerfile
> Update Node to 14.17.2 and 12.22.2

- .github/workflows/ci.yaml
- README.md
- core/nodejs20Action/.dockerignore
- core/nodejs20Action/CHANGELOG.md
- core/nodejs20Action/Dockerfile
- core/nodejs20Action/build.gradle
- tests/dat/docker/nodejs20docker/Dockerfile
- tests/dat/docker/nodejs20docker/build.gradle
- tests/dat/docker/nodejs20docker/package.json
- tests/src/test/scala/runtime/actionContainers/NodeJs20ActionContainerTest.scala
- tests/src/test/scala/runtime/actionContainers/NodeJs20ConcurrentTests.scala
> Initial Nodejs 20 Commit
